export { default as ChorusPedal } from './ChorusPedal'
export { default as DistortionPedal } from './DistortionPedal'
export { default as ReverbPedal } from './ReverbPedal'
export { default as DelayPedal } from './DelayPedal'
export { default as VolumePedal } from './VolumePedal'
export { default as PhaserPedal } from './PhaserPedal'
